# Generated by Django 5.2 on 2025-04-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="had_booked",
            field=models.BooleanField(default=False, verbose_name="Had booked"),
        ),
    ]
