# Generated by Django 5.2 on 2025-04-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_password_reset_token_user_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password_reset_token",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Reset_Token"),
        ),
    ]
