# Generated by Django 5.2 on 2025-05-01 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_password_reset_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["full_name"],
                "permissions": [("can_admin_website", "Can administer the website")],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
