# Generated by Django 5.2 on 2025-04-26 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mealcategory",
            options={"ordering": ["pk"], "verbose_name": "Meal Category", "verbose_name_plural": "Meal Categories"},
        ),
    ]
