# Generated by Django 5.2 on 2025-04-26 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_mealcategory_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meals",
                to="services.mealcategory",
                verbose_name="Menu Category",
            ),
        ),
    ]
