# Generated by Django 5.2 on 2025-04-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_alter_meal_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="image",
            field=models.ImageField(default="static/default_food.png", upload_to="meals/", verbose_name="Image"),
        ),
    ]
