# Generated by Django 5.2 on 2025-04-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_alter_meal_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealcategory",
            name="image",
            field=models.ImageField(default="static/default_food.png", upload_to="menu/", verbose_name="Image"),
        ),
    ]
