# Generated by Django 5.2 on 2025-04-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_alter_mealcategory_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealcategory",
            name="image",
            field=models.ImageField(default="default_food.png", upload_to="menu/", verbose_name="Image"),
        ),
    ]
