# Generated by Django 5.2 on 2025-04-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Service Name")),
                ("description", models.TextField(verbose_name="Service Description")),
                ("image", models.ImageField(upload_to="services/", verbose_name="Service Image")),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Personnel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Personnel Name")),
                ("position", models.CharField(max_length=100, verbose_name="Personnel Position")),
                ("description", models.TextField(verbose_name="Personnel Description")),
                ("quote", models.TextField(verbose_name="Personnel Quote")),
                ("photo", models.ImageField(upload_to="personnel/", verbose_name="Personnel Photo")),
            ],
            options={
                "verbose_name": "Personnel",
                "verbose_name_plural": "Personnel",
                "ordering": ["name"],
                "unique_together": {("name", "position")},
            },
        ),
    ]
