# Generated by Django 5.2 on 2025-04-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Reviewer Name")),
                ("review_text", models.TextField(verbose_name="Review Text")),
                ("rating", models.IntegerField(verbose_name="Rating")),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="Review Date")),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "ordering": ["-date"],
            },
        ),
    ]
