# Generated by Django 5.2 on 2025-04-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_alter_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personnel",
            name="photo",
            field=models.ImageField(
                default="default_person.jpg", upload_to="personnel/", verbose_name="Personnel Photo"
            ),
        ),
    ]
