# Generated by Django 5.2 on 2025-05-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0006_alter_personnel_options_alter_review_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(verbose_name="Rating"),
        ),
    ]
