# Generated by Django 5.2 on 2025-04-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="location",
        ),
        migrations.AlterField(
            model_name="table",
            name="capacity",
            field=models.SmallIntegerField(
                choices=[(2, 2), (4, 4), (6, 6), (8, 8), (10, 10)], verbose_name="Capacity"
            ),
        ),
    ]
