# Generated by Django 5.2 on 2025-04-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0003_remove_table_location_alter_table_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="is_reserved",
            field=models.BooleanField(default=False, verbose_name="Is Reserved"),
        ),
    ]
