# Generated by Django 5.2 on 2025-04-25 05:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0004_table_is_reserved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="total_persons",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)],
                verbose_name="Total Persons",
            ),
        ),
    ]
