# Generated by Django 5.2 on 2025-05-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0005_alter_reservation_total_persons"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
    ]
