# Generated by Django 5.2 on 2025-05-01 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0006_reservation_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="customer",
            new_name="user",
        ),
    ]
