# Generated by Django 5.2 on 2025-05-01 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0009_alter_reservation_options_alter_table_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="total_persons",
            field=models.PositiveIntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)],
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)],
                verbose_name="Total Persons",
            ),
        ),
    ]
