# Generated by Django 5.2 on 2025-05-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0012_alter_reservation_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="user_name",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="User Name"),
        ),
        migrations.AddField(
            model_name="reservation",
            name="user_phone",
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="User Phone"),
        ),
    ]
