# Generated by Django 5.2 on 2025-05-02 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0013_reservation_user_name_reservation_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="number",
            field=models.SmallIntegerField(
                unique=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)],
                verbose_name="Table Number",
            ),
        ),
    ]
